name: Ultimate Ubuntu CloudLab

on:
  workflow_dispatch:

jobs:
  ubuntulab:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Update System
        run: |
          sudo apt-get update

      - name: Install XFCE Desktop and XRDP
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            xfce4 xfce4-goodies \
            xrdp

          echo "startxfce4" > ~/.xsession

          sudo adduser xrdp ssl-cert
          sudo systemctl enable xrdp
          sudo systemctl restart xrdp

      - name: Create Lab User
        run: |
          sudo useradd -m -s /bin/bash cloudlab || true
          echo "cloudlab:P@ssw0rd123" | sudo chpasswd
          sudo usermod -aG sudo cloudlab

  
            sleep 60
          done
